### ISSUE TITLE
pollProjectileHits

### ISSUE THREAD

**Issue by PoSihDun** [martinohanlon/mcpi#11] opened 2020-06-28 19:43 UTC
I had to use a old version of mcpi the other night. trying to use pollProjectileHits but an error that states the BlockEvent in minecraft.py file are out of the arrays range is prompted every time my arrow hits a block. Sorry, I don't have what the error specifically says atm. Note the old mcpi has no problem with my code.

```
def pollProjectileHits(self):
        """Only triggered by projectiles => [BlockEvent]"""
        s = self.conn.sendReceive(b"player.events.projectile.hits")
        events = [e for e in s.split("|") if e]
        results = []
        for e in events:
            info = e.split(",")
            results.append(ProjectileEvent.Hit(
                int(info[0]), 
                int(info[1]), 
                int(info[2]), 
                int(info[3]), 
                info[4],
                info[5])<------- this is where the error is highlighted.
        return results
```
this is a sample of my code.
```
def amenotejikara(): #Teleporting with arrow shots
    for blockhit in mc.player.pollProjectileHits():
        pos = blockhit.pos
        teleport = mc.player.setPos(pos.x, pos.y, pos.z)
```

edited to include code blocks

**Comment by martinohanlon** [comment] 2020-06-28 20:58
Can you let me know which version of RaspberryJuice you are using?

**Comment by PoSihDun** [comment] 2020-06-28 21:28
I used a few version and will check when I get home, but I used 1.12.1 for sure and a few versions before that.

**Comment by PoSihDun** [comment] 2020-06-28 21:35
ive been using this one also

raspberryjuice-1.8tc.jar

**Comment by martinohanlon** [comment] 2020-06-29 15:31
Tested with RaspberryJuice 1.12.1 + mcpi1.2 - I cant find any issues.

![image](https://user-images.githubusercontent.com/2329501/86025125-c16e2980-ba25-11ea-931a-c4c5c3637b5d.png)

I am also confused by your comment

> I had to use a old version of mcpi the other night.

pollProjectileHits didnt exist in any version of mcpi before version 1.2

Closing as unable to reproduce, feel free to reopen if you can provide additional information.

**Closed as completed by martinohanlon** 2020-06-29 15:31 UTC

**Comment by PoSihDun** [comment] 2020-06-30 03:47
![IMG_20200629_213337](https://user-images.githubusercontent.com/31666995/86080952-5aff0080-ba51-11ea-888f-dde7986f7636.jpg)

The picture above is using a version of mcpi saved to my google drive from a while back, it runs the code just fine

![IMG_20200629_214337](https://user-images.githubusercontent.com/31666995/86081093-bb8e3d80-ba51-11ea-8422-9dd54236161b.jpg)
![IMG_20200629_213514](https://user-images.githubusercontent.com/31666995/86081111-ca74f000-ba51-11ea-9b5f-bf6bd7570c04.jpg)
![IMG_20200629_213525](https://user-images.githubusercontent.com/31666995/86081125-d19bfe00-ba51-11ea-8fd1-64c8c142a4f8.jpg)

This is what happens when I try and run the code with version 1.2.

Thanks for your help.
